### ISSUE TITLE
Deleting events doesn't seem to remove impact tags from articles

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#24] opened 2015-07-09 03:33 UTC
After deleting events the article counts versus the event counts are off

![screen shot 2015-07-03 at 14 57 30 pm](https://cloud.githubusercontent.com/assets/498744/8504023/75f18a96-2197-11e5-856f-8f6d73dfd5ff.png)
![screen shot 2015-07-03 at 14 57 39 pm](https://cloud.githubusercontent.com/assets/498744/8504024/75f3d256-2197-11e5-893e-d458c31a1aa1.png)

**Comment by abelsonlive** [comment] 2015-07-09 04:01
So just to clarify: the 4 content items you queried in the second image should not have any events (and therefore impact tags) associated with them?

**Comment by mhkeller** [comment] 2015-07-09 04:48
The first image is of the `content_item` info, returning a bunch of summary information on what impact tag are associated with that `content_item` through its events. The second image is querying events for that content items. 

So the there are 
- two tags of id 7
- one tag of id 6
- one tag of id 8

The event summary info is showing eleven impact tags including those of ids 11, 4, and 1, which (I believe) are from deleted events. It appears that when those events were deleted, the `content_item` didn't update its summary information. I could be wrong and the counts were off to begin, which should be easy enough to check on a few of them — but I think this is more related to deletion.

**Comment by abelsonlive** [comment] 2015-07-12 17:12
Can you walk through exactly the steps you took to generate this error? Starting from a fresh install.  I can't seem to reproduce it.

**Comment by abelsonlive** [comment] 2015-07-12 19:24
Ahh, okay. So the problem is that the event-level `metrics` associated with `content_items` are not updated on event deletion. The same problem will actually hold true for tag creation as well, since these metrics are not calculated at the time of request, but in the background.  I'm gonna close this issue and open a new one that is more informative.

**Closed as completed by abelsonlive** 2015-07-12 19:24 UTC
Labels: bug, newslynx-core
